package minecraft

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class Biome {
    UNKNOWN,
    
    @SerialName("minecraft:ocean")
    OCEAN,
    @SerialName("minecraft:plains")
    PLAINS,
    @SerialName("minecraft:desert")
    DESERT,
    @SerialName("minecraft:mountains")
    MOUNTAINS,
    @SerialName("minecraft:forest")
    FOREST,
    @SerialName("minecraft:taiga")
    TAIGA,
    @SerialName("minecraft:swamp")
    SWAMP,
    @SerialName("minecraft:river")
    RIVER,
    @SerialName("minecraft:nether")
    NETHER,
    @SerialName("minecraft:the_end")
    THE_END,
    @SerialName("minecraft:frozen_ocean")
    FROZEN_OCEAN,
    @SerialName("minecraft:frozen_river")
    FROZEN_RIVER,
    @SerialName("minecraft:snowy_tundra")
    SNOWY_TUNDRA,
    @SerialName("minecraft:snowy_mountains")
    SNOWY_MOUNTAINS,
    @SerialName("minecraft:mushroom_fields")
    MUSHROOM_FIELDS,
    @SerialName("minecraft:mushroom_field_shore")
    MUSHROOM_FIELD_SHORE,
    @SerialName("minecraft:beach")
    BEACH,
    @SerialName("minecraft:desert_hills")
    DESERT_HILLS,
    @SerialName("minecraft:wooded_hills")
    WOODED_HILLS,
    @SerialName("minecraft:taiga_hills")
    TAIGA_HILLS,
    @SerialName("minecraft:mountain_edge")
    MOUNTAIN_EDGE,
    @SerialName("minecraft:jungle")
    JUNGLE,
    @SerialName("minecraft:jungle_hills")
    JUNGLE_HILLS,
    @SerialName("minecraft:jungle_edge")
    JUNGLE_EDGE,
    @SerialName("minecraft:deep_ocean")
    DEEP_OCEAN,
    @SerialName("minecraft:stone_shore")
    STONE_SHORE,
    @SerialName("minecraft:snowy_beach")
    SNOWY_BEACH,
    @SerialName("minecraft:birch_forest")
    BIRCH_FOREST,
    @SerialName("minecraft:birch_forest_hills")
    BIRCH_FOREST_HILLS,
    @SerialName("minecraft:dark_forest")
    DARK_FOREST,
    @SerialName("minecraft:snowy_taiga")
    SNOWY_TAIGA,
    @SerialName("minecraft:snowy_taiga_hills")
    SNOWY_TAIGA_HILLS,
    @SerialName("minecraft:giant_tree_taiga")
    GIANT_TREE_TAIGA,
    @SerialName("minecraft:giant_tree_taiga_hills")
    GIANT_TREE_TAIGA_HILLS,
    @SerialName("minecraft:wooded_mountains")
    WOODED_MOUNTAINS,
    @SerialName("minecraft:savanna")
    SAVANNA,
    @SerialName("minecraft:savanna_plateau")
    SAVANNA_PLATEAU,
    @SerialName("minecraft:badlands")
    BADLANDS,
    @SerialName("minecraft:wooded_badlands_plateau")
    WOODED_BADLANDS_PLATEAU,
    @SerialName("minecraft:badlands_plateau")
    BADLANDS_PLATEAU,
    @SerialName("minecraft:small_end_islands")
    SMALL_END_ISLANDS,
    @SerialName("minecraft:end_midlands")
    END_MIDLANDS,
    @SerialName("minecraft:end_highlands")
    END_HIGHLANDS,
    @SerialName("minecraft:end_barrens")
    END_BARRENS,
    @SerialName("minecraft:warm_ocean")
    WARM_OCEAN,
    @SerialName("minecraft:lukewarm_ocean")
    LUKEWARM_OCEAN,
    @SerialName("minecraft:cold_ocean")
    COLD_OCEAN,
    @SerialName("minecraft:deep_warm_ocean")
    DEEP_WARM_OCEAN,
    @SerialName("minecraft:deep_lukewarm_ocean")
    DEEP_LUKEWARM_OCEAN,
    @SerialName("minecraft:deep_cold_ocean")
    DEEP_COLD_OCEAN,
    @SerialName("minecraft:deep_frozen_ocean")
    DEEP_FROZEN_OCEAN,
    @SerialName("minecraft:sunflower_plains")
    SUNFLOWER_PLAINS,
    @SerialName("minecraft:desert_lakes")
    DESERT_LAKES,
    @SerialName("minecraft:gravelly_mountains")
    GRAVELLY_MOUNTAINS,
    @SerialName("minecraft:flower_forest")
    FLOWER_FOREST,
    @SerialName("minecraft:taiga_mountains")
    TAIGA_MOUNTAINS,
    @SerialName("minecraft:swamp_hills")
    SWAMP_HILLS,
    @SerialName("minecraft:ice_spikes")
    ICE_SPIKES,
    @SerialName("minecraft:modified_jungle")
    MODIFIED_JUNGLE,
    @SerialName("minecraft:modified_jungle_edge")
    MODIFIED_JUNGLE_EDGE,
    @SerialName("minecraft:tall_birch_forest")
    TALL_BIRCH_FOREST,
    @SerialName("minecraft:tall_birch_hills")
    TALL_BIRCH_HILLS,
    @SerialName("minecraft:dark_forest_hills")
    DARK_FOREST_HILLS,
    @SerialName("minecraft:snowy_taiga_mountains")
    SNOWY_TAIGA_MOUNTAINS,
    @SerialName("minecraft:giant_spruce_taiga")
    GIANT_SPRUCE_TAIGA,
    @SerialName("minecraft:giant_spruce_taiga_hills")
    GIANT_SPRUCE_TAIGA_HILLS,
    @SerialName("minecraft:modified_gravelly_mountains")
    MODIFIED_GRAVELLY_MOUNTAINS,
    @SerialName("minecraft:shattered_savanna")
    SHATTERED_SAVANNA,
    @SerialName("minecraft:shattered_savanna_plateau")
    SHATTERED_SAVANNA_PLATEAU,
    @SerialName("minecraft:eroded_badlands")
    ERODED_BADLANDS,
    @SerialName("minecraft:modified_wooded_badlands_plateau")
    MODIFIED_WOODED_BADLANDS_PLATEAU,
    @SerialName("minecraft:modified_badlands_plateau")
    MODIFIED_BADLANDS_PLATEAU,
    @SerialName("minecraft:bamboo_jungle")
    BAMBOO_JUNGLE,
    @SerialName("minecraft:bamboo_jungle_hills")
    BAMBOO_JUNGLE_HILLS,
    @SerialName("minecraft:soul_sand_valley")
    SOUL_SAND_VALLEY,
    @SerialName("minecraft:crimson_forest")
    CRIMSON_FOREST,
    @SerialName("minecraft:warped_forest")
    WARPED_FOREST,
    @SerialName("minecraft:basalt_deltas")
    BASALT_DELTAS,
    @SerialName("minecraft:nether_wastes")
    NETHER_WASTES,
    @SerialName("minecraft:dripstone_caves")
    DRIPSTONE_CAVES,
    @SerialName("minecraft:lush_caves")
    LUSH_CAVES,
    @SerialName("minecraft:meadow")
    MEADOW,
    @SerialName("minecraft:grove")
    GROVE,
    @SerialName("minecraft:snowy_slopes")
    SNOWY_SLOPES,
    @SerialName("minecraft:frozen_peaks")
    FROZEN_PEAKS,
    @SerialName("minecraft:jagged_peaks")
    JAGGED_PEAKS,
    @SerialName("minecraft:stony_peaks")
    STONY_PEAKS,
    @SerialName("minecraft:deep_dark")
    DEEP_DARK,
    @SerialName("minecraft:mangrove_swamp")
    MANGROVE_SWAMP,
    
    // 1.18+ and 1.19+ biomes
    @SerialName("minecraft:old_growth_birch_forest")
    OLD_GROWTH_BIRCH_FOREST,
    @SerialName("minecraft:old_growth_pine_taiga")
    OLD_GROWTH_PINE_TAIGA,
    @SerialName("minecraft:old_growth_spruce_taiga")
    OLD_GROWTH_SPRUCE_TAIGA,
    @SerialName("minecraft:sparse_jungle")
    SPARSE_JUNGLE,
    @SerialName("minecraft:stony_shore")
    STONY_SHORE,
    @SerialName("minecraft:windswept_hills")
    WINDSWEPT_HILLS,
    @SerialName("minecraft:windswept_gravelly_hills")
    WINDSWEPT_GRAVELLY_HILLS,
    @SerialName("minecraft:windswept_forest")
    WINDSWEPT_FOREST,
    @SerialName("minecraft:windswept_savanna")
    WINDSWEPT_SAVANNA,
    @SerialName("minecraft:snowy_plains")
    SNOWY_PLAINS,
    @SerialName("minecraft:snowy_forest")
    SNOWY_FOREST,
    @SerialName("minecraft:wooded_badlands")
    WOODED_BADLANDS,
    
    // 1.20 (Trails & Tales)
    @SerialName("minecraft:cherry_grove")
    CHERRY_GROVE_NEW
}
