package minecraft

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
enum class BlockID {
    @SerialName("minecraft:air")
    AIR,
    @SerialName("minecraft:cave_air")
    CAVE_AIR,
    @SerialName("minecraft:void_air")
    VOID_AIR,
    @SerialName("minecraft:glowstone")
    GLOWSTONE,
    @SerialName("minecraft:shroomlight")
    SHROOMLIGHT,
    @SerialName("minecraft:sea_lantern")
    SEA_LANTERN,
    @SerialName("minecraft:jack_o_lantern")
    JACK_O_LANTERN,
    @SerialName("minecraft:redstone_lamp")
    REDSTONE_LAMP,
    @SerialName("minecraft:grass_block")
    GRASS_BLOCK,
    @SerialName("minecraft:dirt")
    DIRT,
    @SerialName("minecraft:coarse_dirt")
    COARSE_DIRT,
    @SerialName("minecraft:podzol")
    PODZOL,
    @SerialName("minecraft:rooted_dirt")
    ROOTED_DIRT,
    @SerialName("minecraft:mud")
    MUD,
    @SerialName("minecraft:muddy_mangrove_roots")
    MUDDY_MANGROVE_ROOTS,
    @SerialName("minecraft:mycelium")
    MYCELIUM,
    @SerialName("minecraft:grass")
    GRASS,
    @SerialName("minecraft:tall_grass")
    TALL_GRASS,
    @SerialName("minecraft:fern")
    FERN,
    @SerialName("minecraft:large_fern")
    LARGE_FERN,
    @SerialName("minecraft:snow")
    SNOW,
    @SerialName("minecraft:snow_block")
    SNOW_BLOCK,
    @SerialName("minecraft:ice")
    ICE,
    @SerialName("minecraft:packed_ice")
    PACKED_ICE,
    @SerialName("minecraft:blue_ice")
    BLUE_ICE,
    @SerialName("minecraft:frosted_ice")
    FROSTED_ICE,
    @SerialName("minecraft:clay")
    CLAY,
    @SerialName("minecraft:gravel")
    GRAVEL,
    @SerialName("minecraft:sand")
    SAND,
    @SerialName("minecraft:red_sand")
    RED_SAND,
    @SerialName("minecraft:sandstone")
    SANDSTONE,
    @SerialName("minecraft:chiseled_sandstone")
    CHISELED_SANDSTONE,
    @SerialName("minecraft:cut_sandstone")
    CUT_SANDSTONE,
    @SerialName("minecraft:smooth_sandstone")
    SMOOTH_SANDSTONE,
    @SerialName("minecraft:red_sandstone")
    RED_SANDSTONE,
    @SerialName("minecraft:chiseled_red_sandstone")
    CHISELED_RED_SANDSTONE,
    @SerialName("minecraft:cut_red_sandstone")
    CUT_RED_SANDSTONE,
    @SerialName("minecraft:smooth_red_sandstone")
    SMOOTH_RED_SANDSTONE,
    @SerialName("minecraft:dripstone_block")
    DRIPSTONE_BLOCK,
    @SerialName("minecraft:pointed_dripstone")
    POINTED_DRIPSTONE,
    @SerialName("minecraft:calcite")
    CALCITE,
    @SerialName("minecraft:tuff")
    TUFF,
    @SerialName("minecraft:tuff_bricks")
    TUFF_BRICKS,
    @SerialName("minecraft:chiseled_tuff")
    CHISELED_TUFF,
    @SerialName("minecraft:polished_tuff")
    POLISHED_TUFF,
    @SerialName("minecraft:tuff_brick_slab")
    TUFF_BRICK_SLAB,
    @SerialName("minecraft:tuff_brick_stairs")
    TUFF_BRICK_STAIRS,
    @SerialName("minecraft:tuff_brick_wall")
    TUFF_BRICK_WALL,
    @SerialName("minecraft:polished_tuff_slab")
    POLISHED_TUFF_SLAB,
    @SerialName("minecraft:polished_tuff_stairs")
    POLISHED_TUFF_STAIRS,
    @SerialName("minecraft:polished_tuff_wall")
    POLISHED_TUFF_WALL,
    @SerialName("minecraft:netherrack")
    NETHERRACK,
    @SerialName("minecraft:stone")
    STONE,
    @SerialName("minecraft:smooth_stone")
    SMOOTH_STONE,
    @SerialName("minecraft:stone_slab")
    STONE_SLAB,
    @SerialName("minecraft:smooth_stone_slab")
    SMOOTH_STONE_SLAB,
    @SerialName("minecraft:stone_stairs")
    STONE_STAIRS,
    @SerialName("minecraft:cobblestone")
    COBBLESTONE,
    @SerialName("minecraft:mossy_cobblestone")
    MOSSY_COBBLESTONE,
    @SerialName("minecraft:cobblestone_stairs")
    COBBLESTONE_STAIRS,
    @SerialName("minecraft:mossy_cobblestone_stairs")
    MOSSY_COBBLESTONE_STAIRS,
    @SerialName("minecraft:cobblestone_slab")
    COBBLESTONE_SLAB,
    @SerialName("minecraft:mossy_cobblestone_slab")
    MOSSY_COBBLESTONE_SLAB,
    @SerialName("minecraft:cobblestone_wall")
    COBBLESTONE_WALL,
    @SerialName("minecraft:mossy_cobblestone_wall")
    MOSSY_COBBLESTONE_WALL,
    @SerialName("minecraft:stone_bricks")
    STONE_BRICKS,
    @SerialName("minecraft:mossy_stone_bricks")
    MOSSY_STONE_BRICKS,
    @SerialName("minecraft:cracked_stone_bricks")
    CRACKED_STONE_BRICKS,
    @SerialName("minecraft:chiseled_stone_bricks")
    CHISELED_STONE_BRICKS,
    @SerialName("minecraft:stone_brick_slab")
    STONE_BRICK_SLAB,
    @SerialName("minecraft:stone_brick_stairs")
    STONE_BRICK_STAIRS,
    @SerialName("minecraft:stone_brick_wall")
    STONE_BRICK_WALL,
    @SerialName("minecraft:mossy_stone_brick_slab")
    MOSSY_STONE_BRICK_SLAB,
    @SerialName("minecraft:mossy_stone_brick_stairs")
    MOSSY_STONE_BRICK_STAIRS,
    @SerialName("minecraft:mossy_stone_brick_wall")
    MOSSY_STONE_BRICK_WALL,
    @SerialName("minecraft:andesite")
    ANDESITE,
    @SerialName("minecraft:polished_andesite")
    POLISHED_ANDESITE,
    @SerialName("minecraft:andesite_slab")
    ANDESITE_SLAB,
    @SerialName("minecraft:andesite_stairs")
    ANDESITE_STAIRS,
    @SerialName("minecraft:andesite_wall")
    ANDESITE_WALL,
    @SerialName("minecraft:polished_andesite_slab")
    POLISHED_ANDESITE_SLAB,
    @SerialName("minecraft:polished_andesite_stairs")
    POLISHED_ANDESITE_STAIRS,
    @SerialName("minecraft:diorite")
    DIORITE,
    @SerialName("minecraft:polished_diorite")
    POLISHED_DIORITE,
    @SerialName("minecraft:diorite_slab")
    DIORITE_SLAB,
    @SerialName("minecraft:diorite_stairs")
    DIORITE_STAIRS,
    @SerialName("minecraft:diorite_wall")
    DIORITE_WALL,
    @SerialName("minecraft:polished_diorite_slab")
    POLISHED_DIORITE_SLAB,
    @SerialName("minecraft:polished_diorite_stairs")
    POLISHED_DIORITE_STAIRS,
    @SerialName("minecraft:granite")
    GRANITE,
    @SerialName("minecraft:polished_granite")
    POLISHED_GRANITE,
    @SerialName("minecraft:granite_slab")
    GRANITE_SLAB,
    @SerialName("minecraft:granite_stairs")
    GRANITE_STAIRS,
    @SerialName("minecraft:granite_wall")
    GRANITE_WALL,
    @SerialName("minecraft:polished_granite_slab")
    POLISHED_GRANITE_SLAB,
    @SerialName("minecraft:polished_granite_stairs")
    POLISHED_GRANITE_STAIRS,
    @SerialName("minecraft:basalt")
    BASALT,
    @SerialName("minecraft:polished_basalt")
    POLISHED_BASALT,
    @SerialName("minecraft:smooth_basalt")
    SMOOTH_BASALT,
    @SerialName("minecraft:deepslate")
    DEEPSLATE,
    @SerialName("minecraft:cobbled_deepslate")
    COBBLED_DEEPSLATE,
    @SerialName("minecraft:polished_deepslate")
    POLISHED_DEEPSLATE,
    @SerialName("minecraft:cobbled_deepslate_slab")
    COBBLED_DEEPSLATE_SLAB,
    @SerialName("minecraft:polished_deepslate_slab")
    POLISHED_DEEPSLATE_SLAB,
    @SerialName("minecraft:deepslate_brick_slab")
    DEEPSLATE_BRICK_SLAB,
    @SerialName("minecraft:deepslate_tile_slab")
    DEEPSLATE_TILE_SLAB,
    @SerialName("minecraft:cobbled_deepslate_stairs")
    COBBLED_DEEPSLATE_STAIRS,
    @SerialName("minecraft:polished_deepslate_stairs")
    POLISHED_DEEPSLATE_STAIRS,
    @SerialName("minecraft:deepslate_brick_stairs")
    DEEPSLATE_BRICK_STAIRS,
    @SerialName("minecraft:deepslate_tile_stairs")
    DEEPSLATE_TILE_STAIRS,
    @SerialName("minecraft:cobbled_deepslate_wall")
    COBBLED_DEEPSLATE_WALL,
    @SerialName("minecraft:deepslate_brick_wall")
    DEEPSLATE_BRICK_WALL,
    @SerialName("minecraft:deepslate_tile_wall")
    DEEPSLATE_TILE_WALL,
    @SerialName("minecraft:deepslate_bricks")
    DEEPSLATE_BRICKS,
    @SerialName("minecraft:deepslate_tiles")
    DEEPSLATE_TILES,
    @SerialName("minecraft:chiseled_deepslate")
    CHISELED_DEEPSLATE,
    @SerialName("minecraft:cracked_deepslate_bricks")
    CRACKED_DEEPSLATE_BRICKS,
    @SerialName("minecraft:cracked_deepslate_tiles")
    CRACKED_DEEPSLATE_TILES,
    @SerialName("minecraft:reinforced_deepslate")
    REINFORCED_DEEPSLATE,
    @SerialName("minecraft:blackstone")
    BLACKSTONE,
    @SerialName("minecraft:polished_blackstone")
    POLISHED_BLACKSTONE,
    @SerialName("minecraft:polished_blackstone_bricks")
    POLISHED_BLACKSTONE_BRICKS,
    @SerialName("minecraft:cracked_polished_blackstone_bricks")
    CRACKED_POLISHED_BLACKSTONE_BRICKS,
    @SerialName("minecraft:chiseled_polished_blackstone")
    CHISELED_POLISHED_BLACKSTONE,
    @SerialName("minecraft:blackstone_slab")
    BLACKSTONE_SLAB,
    @SerialName("minecraft:blackstone_stairs")
    BLACKSTONE_STAIRS,
    @SerialName("minecraft:blackstone_wall")
    BLACKSTONE_WALL,
    @SerialName("minecraft:polished_blackstone_slab")
    POLISHED_BLACKSTONE_SLAB,
    @SerialName("minecraft:polished_blackstone_stairs")
    POLISHED_BLACKSTONE_STAIRS,
    @SerialName("minecraft:polished_blackstone_wall")
    POLISHED_BLACKSTONE_WALL,
    @SerialName("minecraft:polished_blackstone_brick_slab")
    POLISHED_BLACKSTONE_BRICK_SLAB,
    @SerialName("minecraft:polished_blackstone_brick_stairs")
    POLISHED_BLACKSTONE_BRICK_STAIRS,
    @SerialName("minecraft:polished_blackstone_brick_wall")
    POLISHED_BLACKSTONE_BRICK_WALL,
    @SerialName("minecraft:coal_ore")
    COAL_ORE,
    @SerialName("minecraft:deepslate_coal_ore")
    DEEPSLATE_COAL_ORE,
    @SerialName("minecraft:iron_ore")
    IRON_ORE,
    @SerialName("minecraft:deepslate_iron_ore")
    DEEPSLATE_IRON_ORE,
    @SerialName("minecraft:copper_ore")
    COPPER_ORE,
    @SerialName("minecraft:deepslate_copper_ore")
    DEEPSLATE_COPPER_ORE,
    @SerialName("minecraft:gold_ore")
    GOLD_ORE,
    @SerialName("minecraft:deepslate_gold_ore")
    DEEPSLATE_GOLD_ORE,
    @SerialName("minecraft:redstone_ore")
    REDSTONE_ORE,
    @SerialName("minecraft:deepslate_redstone_ore")
    DEEPSLATE_REDSTONE_ORE,
    @SerialName("minecraft:emerald_ore")
    EMERALD_ORE,
    @SerialName("minecraft:deepslate_emerald_ore")
    DEEPSLATE_EMERALD_ORE,
    @SerialName("minecraft:lapis_ore")
    LAPIS_ORE,
    @SerialName("minecraft:deepslate_lapis_ore")
    DEEPSLATE_LAPIS_ORE,
    @SerialName("minecraft:diamond_ore")
    DIAMOND_ORE,
    @SerialName("minecraft:deepslate_diamond_ore")
    DEEPSLATE_DIAMOND_ORE,
    @SerialName("minecraft:nether_gold_ore")
    NETHER_GOLD_ORE,
    @SerialName("minecraft:nether_quartz_ore")
    NETHER_QUARTZ_ORE,
    @SerialName("minecraft:ancient_debris")
    ANCIENT_DEBRIS,
    @SerialName("minecraft:white_wool")
    WHITE_WOOL,
    @SerialName("minecraft:orange_wool")
    ORANGE_WOOL,
    @SerialName("minecraft:magenta_wool")
    MAGENTA_WOOL,
    @SerialName("minecraft:light_blue_wool")
    LIGHT_BLUE_WOOL,
    @SerialName("minecraft:yellow_wool")
    YELLOW_WOOL,
    @SerialName("minecraft:lime_wool")
    LIME_WOOL,
    @SerialName("minecraft:pink_wool")
    PINK_WOOL,
    @SerialName("minecraft:gray_wool")
    GRAY_WOOL,
    @SerialName("minecraft:light_gray_wool")
    LIGHT_GRAY_WOOL,
    @SerialName("minecraft:cyan_wool")
    CYAN_WOOL,
    @SerialName("minecraft:purple_wool")
    PURPLE_WOOL,
    @SerialName("minecraft:blue_wool")
    BLUE_WOOL,
    @SerialName("minecraft:brown_wool")
    BROWN_WOOL,
    @SerialName("minecraft:green_wool")
    GREEN_WOOL,
    @SerialName("minecraft:red_wool")
    RED_WOOL,
    @SerialName("minecraft:black_wool")
    BLACK_WOOL,
    @SerialName("minecraft:oak_planks")
    OAK_PLANKS,
    @SerialName("minecraft:spruce_planks")
    SPRUCE_PLANKS,
    @SerialName("minecraft:birch_planks")
    BIRCH_PLANKS,
    @SerialName("minecraft:jungle_planks")
    JUNGLE_PLANKS,
    @SerialName("minecraft:acacia_planks")
    ACACIA_PLANKS,
    @SerialName("minecraft:dark_oak_planks")
    DARK_OAK_PLANKS,
    @SerialName("minecraft:mangrove_planks")
    MANGROVE_PLANKS,
    @SerialName("minecraft:bamboo_planks")
    BAMBOO_PLANKS,
    @SerialName("minecraft:bamboo_mosaic")
    BAMBOO_MOSAIC,
    @SerialName("minecraft:cherry_planks")
    CHERRY_PLANKS,
    @SerialName("minecraft:crimson_planks")
    CRIMSON_PLANKS,
    @SerialName("minecraft:warped_planks")
    WARPED_PLANKS,
    @SerialName("minecraft:oak_log")
    OAK_LOG,
    @SerialName("minecraft:spruce_log")
    SPRUCE_LOG,
    @SerialName("minecraft:birch_log")
    BIRCH_LOG,
    @SerialName("minecraft:jungle_log")
    JUNGLE_LOG,
    @SerialName("minecraft:acacia_log")
    ACACIA_LOG,
    @SerialName("minecraft:dark_oak_log")
    DARK_OAK_LOG,
    @SerialName("minecraft:mangrove_log")
    MANGROVE_LOG,
    @SerialName("minecraft:cherry_log")
    CHERRY_LOG,
    @SerialName("minecraft:crimson_stem")
    CRIMSON_STEM,
    @SerialName("minecraft:warped_stem")
    WARPED_STEM,
    @SerialName("minecraft:oak_wood")
    OAK_WOOD,
    @SerialName("minecraft:spruce_wood")
    SPRUCE_WOOD,
    @SerialName("minecraft:birch_wood")
    BIRCH_WOOD,
    @SerialName("minecraft:jungle_wood")
    JUNGLE_WOOD,
    @SerialName("minecraft:acacia_wood")
    ACACIA_WOOD,
    @SerialName("minecraft:dark_oak_wood")
    DARK_OAK_WOOD,
    @SerialName("minecraft:mangrove_wood")
    MANGROVE_WOOD,
    @SerialName("minecraft:cherry_wood")
    CHERRY_WOOD,
    @SerialName("minecraft:crimson_hyphae")
    CRIMSON_HYPHAE,
    @SerialName("minecraft:warped_hyphae")
    WARPED_HYPHAE,
    @SerialName("minecraft:stripped_oak_log")
    STRIPPED_OAK_LOG,
    @SerialName("minecraft:stripped_spruce_log")
    STRIPPED_SPRUCE_LOG,
    @SerialName("minecraft:stripped_birch_log")
    STRIPPED_BIRCH_LOG,
    @SerialName("minecraft:stripped_jungle_log")
    STRIPPED_JUNGLE_LOG,
    @SerialName("minecraft:stripped_acacia_log")
    STRIPPED_ACACIA_LOG,
    @SerialName("minecraft:stripped_dark_oak_log")
    STRIPPED_DARK_OAK_LOG,
    @SerialName("minecraft:stripped_mangrove_log")
    STRIPPED_MANGROVE_LOG,
    @SerialName("minecraft:stripped_cherry_log")
    STRIPPED_CHERRY_LOG,
    @SerialName("minecraft:stripped_crimson_stem")
    STRIPPED_CRIMSON_STEM,
    @SerialName("minecraft:stripped_warped_stem")
    STRIPPED_WARPED_STEM,
    @SerialName("minecraft:stripped_oak_wood")
    STRIPPED_OAK_WOOD,
    @SerialName("minecraft:stripped_spruce_wood")
    STRIPPED_SPRUCE_WOOD,
    @SerialName("minecraft:stripped_birch_wood")
    STRIPPED_BIRCH_WOOD,
    @SerialName("minecraft:stripped_jungle_wood")
    STRIPPED_JUNGLE_WOOD,
    @SerialName("minecraft:stripped_acacia_wood")
    STRIPPED_ACACIA_WOOD,
    @SerialName("minecraft:stripped_dark_oak_wood")
    STRIPPED_DARK_OAK_WOOD,
    @SerialName("minecraft:stripped_mangrove_wood")
    STRIPPED_MANGROVE_WOOD,
    @SerialName("minecraft:stripped_cherry_wood")
    STRIPPED_CHERRY_WOOD,
    @SerialName("minecraft:stripped_crimson_hyphae")
    STRIPPED_CRIMSON_HYPHAE,
    @SerialName("minecraft:stripped_warped_hyphae")
    STRIPPED_WARPED_HYPHAE,
    @SerialName("minecraft:oak_stairs")
    OAK_STAIRS,
    @SerialName("minecraft:spruce_stairs")
    SPRUCE_STAIRS,
    @SerialName("minecraft:birch_stairs")
    BIRCH_STAIRS,
    @SerialName("minecraft:jungle_stairs")
    JUNGLE_STAIRS,
    @SerialName("minecraft:acacia_stairs")
    ACACIA_STAIRS,
    @SerialName("minecraft:dark_oak_stairs")
    DARK_OAK_STAIRS,
    @SerialName("minecraft:mangrove_stairs")
    MANGROVE_STAIRS,
    @SerialName("minecraft:bamboo_stairs")
    BAMBOO_STAIRS,
    @SerialName("minecraft:bamboo_mosaic_stairs")
    BAMBOO_MOSAIC_STAIRS,
    @SerialName("minecraft:cherry_stairs")
    CHERRY_STAIRS,
    @SerialName("minecraft:crimson_stairs")
    CRIMSON_STAIRS,
    @SerialName("minecraft:warped_stairs")
    WARPED_STAIRS,
    @SerialName("minecraft:sandstone_stairs")
    SANDSTONE_STAIRS,
    @SerialName("minecraft:smooth_sandstone_stairs")
    SMOOTH_SANDSTONE_STAIRS,
    @SerialName("minecraft:red_sandstone_stairs")
    RED_SANDSTONE_STAIRS,
    @SerialName("minecraft:smooth_red_sandstone_stairs")
    SMOOTH_RED_SANDSTONE_STAIRS,
    @SerialName("minecraft:oak_slab")
    OAK_SLAB,
    @SerialName("minecraft:spruce_slab")
    SPRUCE_SLAB,
    @SerialName("minecraft:birch_slab")
    BIRCH_SLAB,
    @SerialName("minecraft:jungle_slab")
    JUNGLE_SLAB,
    @SerialName("minecraft:acacia_slab")
    ACACIA_SLAB,
    @SerialName("minecraft:dark_oak_slab")
    DARK_OAK_SLAB,
    @SerialName("minecraft:mangrove_slab")
    MANGROVE_SLAB,
    @SerialName("minecraft:bamboo_slab")
    BAMBOO_SLAB,
    @SerialName("minecraft:bamboo_mosaic_slab")
    BAMBOO_MOSAIC_SLAB,
    @SerialName("minecraft:cherry_slab")
    CHERRY_SLAB,
    @SerialName("minecraft:crimson_slab")
    CRIMSON_SLAB,
    @SerialName("minecraft:warped_slab")
    WARPED_SLAB,
    @SerialName("minecraft:sandstone_slab")
    SANDSTONE_SLAB,
    @SerialName("minecraft:cut_sandstone_slab")
    CUT_SANDSTONE_SLAB,
    @SerialName("minecraft:smooth_sandstone_slab")
    SMOOTH_SANDSTONE_SLAB,
    @SerialName("minecraft:red_sandstone_slab")
    RED_SANDSTONE_SLAB,
    @SerialName("minecraft:cut_red_sandstone_slab")
    CUT_RED_SANDSTONE_SLAB,
    @SerialName("minecraft:smooth_red_sandstone_slab")
    SMOOTH_RED_SANDSTONE_SLAB,
    @SerialName("minecraft:sandstone_wall")
    SANDSTONE_WALL,
    @SerialName("minecraft:red_sandstone_wall")
    RED_SANDSTONE_WALL,
    @SerialName("minecraft:oak_fence")
    OAK_FENCE,
    @SerialName("minecraft:spruce_fence")
    SPRUCE_FENCE,
    @SerialName("minecraft:birch_fence")
    BIRCH_FENCE,
    @SerialName("minecraft:jungle_fence")
    JUNGLE_FENCE,
    @SerialName("minecraft:acacia_fence")
    ACACIA_FENCE,
    @SerialName("minecraft:dark_oak_fence")
    DARK_OAK_FENCE,
    @SerialName("minecraft:mangrove_fence")
    MANGROVE_FENCE,
    @SerialName("minecraft:bamboo_fence")
    BAMBOO_FENCE,
    @SerialName("minecraft:bamboo_mosaic_fence")
    BAMBOO_MOSAIC_FENCE,
    @SerialName("minecraft:cherry_fence")
    CHERRY_FENCE,
    @SerialName("minecraft:crimson_fence")
    CRIMSON_FENCE,
    @SerialName("minecraft:warped_fence")
    WARPED_FENCE,
    @SerialName("minecraft:oak_fence_gate")
    OAK_FENCE_GATE,
    @SerialName("minecraft:spruce_fence_gate")
    SPRUCE_FENCE_GATE,
    @SerialName("minecraft:birch_fence_gate")
    BIRCH_FENCE_GATE,
    @SerialName("minecraft:jungle_fence_gate")
    JUNGLE_FENCE_GATE,
    @SerialName("minecraft:acacia_fence_gate")
    ACACIA_FENCE_GATE,
    @SerialName("minecraft:dark_oak_fence_gate")
    DARK_OAK_FENCE_GATE,
    @SerialName("minecraft:mangrove_fence_gate")
    MANGROVE_FENCE_GATE,
    @SerialName("minecraft:bamboo_fence_gate")
    BAMBOO_FENCE_GATE,
    @SerialName("minecraft:cherry_fence_gate")
    CHERRY_FENCE_GATE,
    @SerialName("minecraft:crimson_fence_gate")
    CRIMSON_FENCE_GATE,
    @SerialName("minecraft:warped_fence_gate")
    WARPED_FENCE_GATE,
    @SerialName("minecraft:oak_door")
    OAK_DOOR,
    @SerialName("minecraft:spruce_door")
    SPRUCE_DOOR,
    @SerialName("minecraft:birch_door")
    BIRCH_DOOR,
    @SerialName("minecraft:jungle_door")
    JUNGLE_DOOR,
    @SerialName("minecraft:acacia_door")
    ACACIA_DOOR,
    @SerialName("minecraft:dark_oak_door")
    DARK_OAK_DOOR,
    @SerialName("minecraft:mangrove_door")
    MANGROVE_DOOR,
    @SerialName("minecraft:bamboo_door")
    BAMBOO_DOOR,
    @SerialName("minecraft:cherry_door")
    CHERRY_DOOR,
    @SerialName("minecraft:crimson_door")
    CRIMSON_DOOR,
    @SerialName("minecraft:warped_door")
    WARPED_DOOR,
    @SerialName("minecraft:oak_trapdoor")
    OAK_TRAPDOOR,
    @SerialName("minecraft:spruce_trapdoor")
    SPRUCE_TRAPDOOR,
    @SerialName("minecraft:birch_trapdoor")
    BIRCH_TRAPDOOR,
    @SerialName("minecraft:jungle_trapdoor")
    JUNGLE_TRAPDOOR,
    @SerialName("minecraft:acacia_trapdoor")
    ACACIA_TRAPDOOR,
    @SerialName("minecraft:dark_oak_trapdoor")
    DARK_OAK_TRAPDOOR,
    @SerialName("minecraft:mangrove_trapdoor")
    MANGROVE_TRAPDOOR,
    @SerialName("minecraft:bamboo_trapdoor")
    BAMBOO_TRAPDOOR,
    @SerialName("minecraft:cherry_trapdoor")
    CHERRY_TRAPDOOR,
    @SerialName("minecraft:crimson_trapdoor")
    CRIMSON_TRAPDOOR,
    @SerialName("minecraft:warped_trapdoor")
    WARPED_TRAPDOOR,
    @SerialName("minecraft:oak_sign")
    OAK_SIGN,
    @SerialName("minecraft:spruce_sign")
    SPRUCE_SIGN,
    @SerialName("minecraft:birch_sign")
    BIRCH_SIGN,
    @SerialName("minecraft:jungle_sign")
    JUNGLE_SIGN,
    @SerialName("minecraft:acacia_sign")
    ACACIA_SIGN,
    @SerialName("minecraft:dark_oak_sign")
    DARK_OAK_SIGN,
    @SerialName("minecraft:mangrove_sign")
    MANGROVE_SIGN,
    @SerialName("minecraft:bamboo_sign")
    BAMBOO_SIGN,
    @SerialName("minecraft:cherry_sign")
    CHERRY_SIGN,
    @SerialName("minecraft:crimson_sign")
    CRIMSON_SIGN,
    @SerialName("minecraft:warped_sign")
    WARPED_SIGN,
    @SerialName("minecraft:oak_wall_sign")
    OAK_WALL_SIGN,
    @SerialName("minecraft:spruce_wall_sign")
    SPRUCE_WALL_SIGN,
    @SerialName("minecraft:birch_wall_sign")
    BIRCH_WALL_SIGN,
    @SerialName("minecraft:jungle_wall_sign")
    JUNGLE_WALL_SIGN,
    @SerialName("minecraft:acacia_wall_sign")
    ACACIA_WALL_SIGN,
    @SerialName("minecraft:dark_oak_wall_sign")
    DARK_OAK_WALL_SIGN,
    @SerialName("minecraft:mangrove_wall_sign")
    MANGROVE_WALL_SIGN,
    @SerialName("minecraft:bamboo_wall_sign")
    BAMBOO_WALL_SIGN,
    @SerialName("minecraft:cherry_wall_sign")
    CHERRY_WALL_SIGN,
    @SerialName("minecraft:crimson_wall_sign")
    CRIMSON_WALL_SIGN,
    @SerialName("minecraft:warped_wall_sign")
    WARPED_WALL_SIGN,
    @SerialName("minecraft:oak_hanging_sign")
    OAK_HANGING_SIGN,
    @SerialName("minecraft:spruce_hanging_sign")
    SPRUCE_HANGING_SIGN,
    @SerialName("minecraft:birch_hanging_sign")
    BIRCH_HANGING_SIGN,
    @SerialName("minecraft:jungle_hanging_sign")
    JUNGLE_HANGING_SIGN,
    @SerialName("minecraft:acacia_hanging_sign")
    ACACIA_HANGING_SIGN,
    @SerialName("minecraft:dark_oak_hanging_sign")
    DARK_OAK_HANGING_SIGN,
    @SerialName("minecraft:mangrove_hanging_sign")
    MANGROVE_HANGING_SIGN,
    @SerialName("minecraft:bamboo_hanging_sign")
    BAMBOO_HANGING_SIGN,
    @SerialName("minecraft:cherry_hanging_sign")
    CHERRY_HANGING_SIGN,
    @SerialName("minecraft:crimson_hanging_sign")
    CRIMSON_HANGING_SIGN,
    @SerialName("minecraft:warped_hanging_sign")
    WARPED_HANGING_SIGN,
    @SerialName("minecraft:oak_hanging_wall_sign")
    OAK_HANGING_WALL_SIGN,
    @SerialName("minecraft:spruce_hanging_wall_sign")
    SPRUCE_HANGING_WALL_SIGN,
    @SerialName("minecraft:birch_hanging_wall_sign")
    BIRCH_HANGING_WALL_SIGN,
    @SerialName("minecraft:jungle_hanging_wall_sign")
    JUNGLE_HANGING_WALL_SIGN,
    @SerialName("minecraft:acacia_hanging_wall_sign")
    ACACIA_HANGING_WALL_SIGN,
    @SerialName("minecraft:dark_oak_hanging_wall_sign")
    DARK_OAK_HANGING_WALL_SIGN,
    @SerialName("minecraft:mangrove_hanging_wall_sign")
    MANGROVE_HANGING_WALL_SIGN,
    @SerialName("minecraft:bamboo_hanging_wall_sign")
    BAMBOO_HANGING_WALL_SIGN,
    @SerialName("minecraft:cherry_hanging_wall_sign")
    CHERRY_HANGING_WALL_SIGN,
    @SerialName("minecraft:crimson_hanging_wall_sign")
    CRIMSON_HANGING_WALL_SIGN,
    @SerialName("minecraft:warped_hanging_wall_sign")
    WARPED_HANGING_WALL_SIGN,
    @SerialName("minecraft:oak_button")
    OAK_BUTTON,
    @SerialName("minecraft:spruce_button")
    SPRUCE_BUTTON,
    @SerialName("minecraft:birch_button")
    BIRCH_BUTTON,
    @SerialName("minecraft:jungle_button")
    JUNGLE_BUTTON,
    @SerialName("minecraft:acacia_button")
    ACACIA_BUTTON,
    @SerialName("minecraft:dark_oak_button")
    DARK_OAK_BUTTON,
    @SerialName("minecraft:mangrove_button")
    MANGROVE_BUTTON,
    @SerialName("minecraft:bamboo_button")
    BAMBOO_BUTTON,
    @SerialName("minecraft:cherry_button")
    CHERRY_BUTTON,
    @SerialName("minecraft:crimson_button")
    CRIMSON_BUTTON,
    @SerialName("minecraft:warped_button")
    WARPED_BUTTON,
    @SerialName("minecraft:stone_button")
    STONE_BUTTON,
    @SerialName("minecraft:oak_pressure_plate")
    OAK_PRESSURE_PLATE,
    @SerialName("minecraft:spruce_pressure_plate")
    SPRUCE_PRESSURE_PLATE,
    @SerialName("minecraft:birch_pressure_plate")
    BIRCH_PRESSURE_PLATE,
    @SerialName("minecraft:jungle_pressure_plate")
    JUNGLE_PRESSURE_PLATE,
    @SerialName("minecraft:acacia_pressure_plate")
    ACACIA_PRESSURE_PLATE,
    @SerialName("minecraft:dark_oak_pressure_plate")
    DARK_OAK_PRESSURE_PLATE,
    @SerialName("minecraft:mangrove_pressure_plate")
    MANGROVE_PRESSURE_PLATE,
    @SerialName("minecraft:bamboo_pressure_plate")
    BAMBOO_PRESSURE_PLATE,
    @SerialName("minecraft:cherry_pressure_plate")
    CHERRY_PRESSURE_PLATE,
    @SerialName("minecraft:crimson_pressure_plate")
    CRIMSON_PRESSURE_PLATE,
    @SerialName("minecraft:warped_pressure_plate")
    WARPED_PRESSURE_PLATE,
    @SerialName("minecraft:stone_pressure_plate")
    STONE_PRESSURE_PLATE,
    @SerialName("minecraft:water")
    WATER,
    @SerialName("minecraft:lava")
    LAVA,
    @SerialName("minecraft:bubble_column")
    BUBBLE_COLUMN,
    @SerialName("minecraft:kelp")
    KELP,
    @SerialName("minecraft:kelp_plant")
    KELP_PLANT,
    @SerialName("minecraft:seagrass")
    SEAGRASS,
    @SerialName("minecraft:tall_seagrass")
    TALL_SEAGRASS,
    @SerialName("minecraft:cauldron")
    CAULDRON,
    @SerialName("minecraft:water_cauldron")
    WATER_CAULDRON,
    @SerialName("minecraft:lava_cauldron")
    LAVA_CAULDRON,
    @SerialName("minecraft:powder_snow_cauldron")
    POWDER_SNOW_CAULDRON,
    @SerialName("minecraft:chain")
    CHAIN,
    @SerialName("minecraft:iron_bars")
    IRON_BARS,
    @SerialName("minecraft:bedrock")
    BEDROCK,
    @SerialName("minecraft:player_head")
    PLAYER_HEAD,
    @SerialName("minecraft:nether_bricks")
    NETHER_BRICKS,
    @SerialName("minecraft:nether_brick_slab")
    NETHER_BRICK_SLAB,
    @SerialName("minecraft:nether_brick_stairs")
    NETHER_BRICK_STAIRS,
    @SerialName("minecraft:nether_brick_wall")
    NETHER_BRICK_WALL,
    @SerialName("minecraft:nether_brick_fence")
    NETHER_BRICK_FENCE,
    @SerialName("minecraft:chiseled_nether_bricks")
    CHISELED_NETHER_BRICKS,
    @SerialName("minecraft:cracked_nether_bricks")
    CRACKED_NETHER_BRICKS,
    @SerialName("minecraft:red_nether_bricks")
    RED_NETHER_BRICKS,
    @SerialName("minecraft:red_nether_brick_slab")
    RED_NETHER_BRICK_SLAB,
    @SerialName("minecraft:red_nether_brick_stairs")
    RED_NETHER_BRICK_STAIRS,
    @SerialName("minecraft:red_nether_brick_wall")
    RED_NETHER_BRICK_WALL,
    @SerialName("minecraft:red_nether_brick_fence")
    RED_NETHER_BRICK_FENCE,
    @SerialName("minecraft:white_concrete")
    WHITE_CONCRETE,
    @SerialName("minecraft:orange_concrete")
    ORANGE_CONCRETE,
    @SerialName("minecraft:magenta_concrete")
    MAGENTA_CONCRETE,
    @SerialName("minecraft:light_blue_concrete")
    LIGHT_BLUE_CONCRETE,
    @SerialName("minecraft:yellow_concrete")
    YELLOW_CONCRETE,
    @SerialName("minecraft:lime_concrete")
    LIME_CONCRETE,
    @SerialName("minecraft:pink_concrete")
    PINK_CONCRETE,
    @SerialName("minecraft:gray_concrete")
    GRAY_CONCRETE,
    @SerialName("minecraft:light_gray_concrete")
    LIGHT_GRAY_CONCRETE,
    @SerialName("minecraft:cyan_concrete")
    CYAN_CONCRETE,
    @SerialName("minecraft:purple_concrete")
    PURPLE_CONCRETE,
    @SerialName("minecraft:blue_concrete")
    BLUE_CONCRETE,
    @SerialName("minecraft:brown_concrete")
    BROWN_CONCRETE,
    @SerialName("minecraft:green_concrete")
    GREEN_CONCRETE,
    @SerialName("minecraft:red_concrete")
    RED_CONCRETE,
    @SerialName("minecraft:black_concrete")
    BLACK_CONCRETE,
    @SerialName("minecraft:white_concrete_powder")
    WHITE_CONCRETE_POWDER,
    @SerialName("minecraft:orange_concrete_powder")
    ORANGE_CONCRETE_POWDER,
    @SerialName("minecraft:magenta_concrete_powder")
    MAGENTA_CONCRETE_POWDER,
    @SerialName("minecraft:light_blue_concrete_powder")
    LIGHT_BLUE_CONCRETE_POWDER,
    @SerialName("minecraft:yellow_concrete_powder")
    YELLOW_CONCRETE_POWDER,
    @SerialName("minecraft:lime_concrete_powder")
    LIME_CONCRETE_POWDER,
    @SerialName("minecraft:pink_concrete_powder")
    PINK_CONCRETE_POWDER,
    @SerialName("minecraft:gray_concrete_powder")
    GRAY_CONCRETE_POWDER,
    @SerialName("minecraft:light_gray_concrete_powder")
    LIGHT_GRAY_CONCRETE_POWDER,
    @SerialName("minecraft:cyan_concrete_powder")
    CYAN_CONCRETE_POWDER,
    @SerialName("minecraft:purple_concrete_powder")
    PURPLE_CONCRETE_POWDER,
    @SerialName("minecraft:blue_concrete_powder")
    BLUE_CONCRETE_POWDER,
    @SerialName("minecraft:brown_concrete_powder")
    BROWN_CONCRETE_POWDER,
    @SerialName("minecraft:green_concrete_powder")
    GREEN_CONCRETE_POWDER,
    @SerialName("minecraft:red_concrete_powder")
    RED_CONCRETE_POWDER,
    @SerialName("minecraft:black_concrete_powder")
    BLACK_CONCRETE_POWDER,
    @SerialName("minecraft:terracotta")
    TERRACOTTA,
    @SerialName("minecraft:white_terracotta")
    WHITE_TERRACOTTA,
    @SerialName("minecraft:orange_terracotta")
    ORANGE_TERRACOTTA,
    @SerialName("minecraft:magenta_terracotta")
    MAGENTA_TERRACOTTA,
    @SerialName("minecraft:light_blue_terracotta")
    LIGHT_BLUE_TERRACOTTA,
    @SerialName("minecraft:yellow_terracotta")
    YELLOW_TERRACOTTA,
    @SerialName("minecraft:lime_terracotta")
    LIME_TERRACOTTA,
    @SerialName("minecraft:pink_terracotta")
    PINK_TERRACOTTA,
    @SerialName("minecraft:gray_terracotta")
    GRAY_TERRACOTTA,
    @SerialName("minecraft:light_gray_terracotta")
    LIGHT_GRAY_TERRACOTTA,
    @SerialName("minecraft:cyan_terracotta")
    CYAN_TERRACOTTA,
    @SerialName("minecraft:purple_terracotta")
    PURPLE_TERRACOTTA,
    @SerialName("minecraft:blue_terracotta")
    BLUE_TERRACOTTA,
    @SerialName("minecraft:brown_terracotta")
    BROWN_TERRACOTTA,
    @SerialName("minecraft:green_terracotta")
    GREEN_TERRACOTTA,
    @SerialName("minecraft:red_terracotta")
    RED_TERRACOTTA,
    @SerialName("minecraft:black_terracotta")
    BLACK_TERRACOTTA,
    @SerialName("minecraft:packed_mud")
    PACKED_MUD,
    @SerialName("minecraft:mud_bricks")
    MUD_BRICKS,
    @SerialName("minecraft:mud_brick_slab")
    MUD_BRICK_SLAB,
    @SerialName("minecraft:mud_brick_stairs")
    MUD_BRICK_STAIRS,
    @SerialName("minecraft:mud_brick_wall")
    MUD_BRICK_WALL,
    @SerialName("minecraft:prismarine")
    PRISMARINE,
    @SerialName("minecraft:prismarine_bricks")
    PRISMARINE_BRICKS,
    @SerialName("minecraft:dark_prismarine")
    DARK_PRISMARINE,
    @SerialName("minecraft:prismarine_slab")
    PRISMARINE_SLAB,
    @SerialName("minecraft:prismarine_brick_slab")
    PRISMARINE_BRICK_SLAB,
    @SerialName("minecraft:dark_prismarine_slab")
    DARK_PRISMARINE_SLAB,
    @SerialName("minecraft:prismarine_stairs")
    PRISMARINE_STAIRS,
    @SerialName("minecraft:prismarine_brick_stairs")
    PRISMARINE_BRICK_STAIRS,
    @SerialName("minecraft:dark_prismarine_stairs")
    DARK_PRISMARINE_STAIRS,
    @SerialName("minecraft:prismarine_wall")
    PRISMARINE_WALL,
    @SerialName("minecraft:quartz_block")
    QUARTZ_BLOCK,
    @SerialName("minecraft:smooth_quartz")
    SMOOTH_QUARTZ,
    @SerialName("minecraft:chiseled_quartz_block")
    CHISELED_QUARTZ_BLOCK,
    @SerialName("minecraft:quartz_pillar")
    QUARTZ_PILLAR,
    @SerialName("minecraft:quartz_bricks")
    QUARTZ_BRICKS,
    @SerialName("minecraft:quartz_slab")
    QUARTZ_SLAB,
    @SerialName("minecraft:smooth_quartz_slab")
    SMOOTH_QUARTZ_SLAB,
    @SerialName("minecraft:quartz_stairs")
    QUARTZ_STAIRS,
    @SerialName("minecraft:smooth_quartz_stairs")
    SMOOTH_QUARTZ_STAIRS,
    @SerialName("minecraft:purpur_block")
    PURPUR_BLOCK,
    @SerialName("minecraft:purpur_pillar")
    PURPUR_PILLAR,
    @SerialName("minecraft:purpur_stairs")
    PURPUR_STAIRS,
    @SerialName("minecraft:purpur_slab")
    PURPUR_SLAB,
    @SerialName("minecraft:copper_block")
    COPPER_BLOCK,
    @SerialName("minecraft:cut_copper")
    CUT_COPPER,
    @SerialName("minecraft:cut_copper_slab")
    CUT_COPPER_SLAB,
    @SerialName("minecraft:cut_copper_stairs")
    CUT_COPPER_STAIRS,
    @SerialName("minecraft:exposed_copper")
    EXPOSED_COPPER,
    @SerialName("minecraft:exposed_cut_copper")
    EXPOSED_CUT_COPPER,
    @SerialName("minecraft:exposed_cut_copper_slab")
    EXPOSED_CUT_COPPER_SLAB,
    @SerialName("minecraft:exposed_cut_copper_stairs")
    EXPOSED_CUT_COPPER_STAIRS,
    @SerialName("minecraft:weathered_copper")
    WEATHERED_COPPER,
    @SerialName("minecraft:weathered_cut_copper")
    WEATHERED_CUT_COPPER,
    @SerialName("minecraft:weathered_cut_copper_slab")
    WEATHERED_CUT_COPPER_SLAB,
    @SerialName("minecraft:weathered_cut_copper_stairs")
    WEATHERED_CUT_COPPER_STAIRS,
    @SerialName("minecraft:oxidized_copper")
    OXIDIZED_COPPER,
    @SerialName("minecraft:oxidized_cut_copper")
    OXIDIZED_CUT_COPPER,
    @SerialName("minecraft:oxidized_cut_copper_slab")
    OXIDIZED_CUT_COPPER_SLAB,
    @SerialName("minecraft:oxidized_cut_copper_stairs")
    OXIDIZED_CUT_COPPER_STAIRS,
    @SerialName("minecraft:waxed_copper_block")
    WAXED_COPPER_BLOCK,
    @SerialName("minecraft:waxed_cut_copper")
    WAXED_CUT_COPPER,
    @SerialName("minecraft:waxed_cut_copper_slab")
    WAXED_CUT_COPPER_SLAB,
    @SerialName("minecraft:waxed_cut_copper_stairs")
    WAXED_CUT_COPPER_STAIRS,
    @SerialName("minecraft:waxed_exposed_copper")
    WAXED_EXPOSED_COPPER,
    @SerialName("minecraft:waxed_exposed_cut_copper")
    WAXED_EXPOSED_CUT_COPPER,
    @SerialName("minecraft:waxed_exposed_cut_copper_slab")
    WAXED_EXPOSED_CUT_COPPER_SLAB,
    @SerialName("minecraft:waxed_exposed_cut_copper_stairs")
    WAXED_EXPOSED_CUT_COPPER_STAIRS,
    @SerialName("minecraft:waxed_weathered_copper")
    WAXED_WEATHERED_COPPER,
    @SerialName("minecraft:waxed_weathered_cut_copper")
    WAXED_WEATHERED_CUT_COPPER,
    @SerialName("minecraft:waxed_weathered_cut_copper_slab")
    WAXED_WEATHERED_CUT_COPPER_SLAB,
    @SerialName("minecraft:waxed_weathered_cut_copper_stairs")
    WAXED_WEATHERED_CUT_COPPER_STAIRS,
    @SerialName("minecraft:waxed_oxidized_copper")
    WAXED_OXIDIZED_COPPER,
    @SerialName("minecraft:waxed_oxidized_cut_copper")
    WAXED_OXIDIZED_CUT_COPPER,
    @SerialName("minecraft:waxed_oxidized_cut_copper_slab")
    WAXED_OXIDIZED_CUT_COPPER_SLAB,
    @SerialName("minecraft:waxed_oxidized_cut_copper_stairs")
    WAXED_OXIDIZED_CUT_COPPER_STAIRS,
    @SerialName("minecraft:glass")
    GLASS,
    @SerialName("minecraft:white_stained_glass")
    WHITE_STAINED_GLASS,
    @SerialName("minecraft:orange_stained_glass")
    ORANGE_STAINED_GLASS,
    @SerialName("minecraft:magenta_stained_glass")
    MAGENTA_STAINED_GLASS,
    @SerialName("minecraft:light_blue_stained_glass")
    LIGHT_BLUE_STAINED_GLASS,
    @SerialName("minecraft:yellow_stained_glass")
    YELLOW_STAINED_GLASS,
    @SerialName("minecraft:lime_stained_glass")
    LIME_STAINED_GLASS,
    @SerialName("minecraft:pink_stained_glass")
    PINK_STAINED_GLASS,
    @SerialName("minecraft:gray_stained_glass")
    GRAY_STAINED_GLASS,
    @SerialName("minecraft:light_gray_stained_glass")
    LIGHT_GRAY_STAINED_GLASS,
    @SerialName("minecraft:cyan_stained_glass")
    CYAN_STAINED_GLASS,
    @SerialName("minecraft:purple_stained_glass")
    PURPLE_STAINED_GLASS,
    @SerialName("minecraft:blue_stained_glass")
    BLUE_STAINED_GLASS,
    @SerialName("minecraft:brown_stained_glass")
    BROWN_STAINED_GLASS,
    @SerialName("minecraft:green_stained_glass")
    GREEN_STAINED_GLASS,
    @SerialName("minecraft:red_stained_glass")
    RED_STAINED_GLASS,
    @SerialName("minecraft:black_stained_glass")
    BLACK_STAINED_GLASS,
    @SerialName("minecraft:glass_pane")
    GLASS_PANE,
    @SerialName("minecraft:white_stained_glass_pane")
    WHITE_STAINED_GLASS_PANE,
    @SerialName("minecraft:orange_stained_glass_pane")
    ORANGE_STAINED_GLASS_PANE,
    @SerialName("minecraft:magenta_stained_glass_pane")
    MAGENTA_STAINED_GLASS_PANE,
    @SerialName("minecraft:light_blue_stained_glass_pane")
    LIGHT_BLUE_STAINED_GLASS_PANE,
    @SerialName("minecraft:yellow_stained_glass_pane")
    YELLOW_STAINED_GLASS_PANE,
    @SerialName("minecraft:lime_stained_glass_pane")
    LIME_STAINED_GLASS_PANE,
    @SerialName("minecraft:pink_stained_glass_pane")
    PINK_STAINED_GLASS_PANE,
    @SerialName("minecraft:gray_stained_glass_pane")
    GRAY_STAINED_GLASS_PANE,
    @SerialName("minecraft:light_gray_stained_glass_pane")
    LIGHT_GRAY_STAINED_GLASS_PANE,
    @SerialName("minecraft:cyan_stained_glass_pane")
    CYAN_STAINED_GLASS_PANE,
    @SerialName("minecraft:purple_stained_glass_pane")
    PURPLE_STAINED_GLASS_PANE,
    @SerialName("minecraft:blue_stained_glass_pane")
    BLUE_STAINED_GLASS_PANE,
    @SerialName("minecraft:brown_stained_glass_pane")
    BROWN_STAINED_GLASS_PANE,
    @SerialName("minecraft:green_stained_glass_pane")
    GREEN_STAINED_GLASS_PANE,
    @SerialName("minecraft:red_stained_glass_pane")
    RED_STAINED_GLASS_PANE,
    @SerialName("minecraft:black_stained_glass_pane")
    BLACK_STAINED_GLASS_PANE,
    @SerialName("minecraft:decorated_pot")
    DECORATED_POT,
    @SerialName("minecraft:crafting_table")
    CRAFTING_TABLE,
    @SerialName("minecraft:furnace")
    FURNACE,
    @SerialName("minecraft:blast_furnace")
    BLAST_FURNACE,
    @SerialName("minecraft:smoker")
    SMOKER,
    @SerialName("minecraft:cartography_table")
    CARTOGRAPHY_TABLE,
    @SerialName("minecraft:loom")
    LOOM,
    @SerialName("minecraft:barrel")
    BARREL,
    @SerialName("minecraft:chest")
    CHEST,
    @SerialName("minecraft:trapped_chest")
    TRAPPED_CHEST,
    @SerialName("minecraft:ender_chest")
    ENDER_CHEST,
    @SerialName("minecraft:shulker_box")
    SHULKER_BOX,
    @SerialName("minecraft:white_shulker_box")
    WHITE_SHULKER_BOX,
    @SerialName("minecraft:orange_shulker_box")
    ORANGE_SHULKER_BOX,
    @SerialName("minecraft:magenta_shulker_box")
    MAGENTA_SHULKER_BOX,
    @SerialName("minecraft:light_blue_shulker_box")
    LIGHT_BLUE_SHULKER_BOX,
    @SerialName("minecraft:yellow_shulker_box")
    YELLOW_SHULKER_BOX,
    @SerialName("minecraft:lime_shulker_box")
    LIME_SHULKER_BOX,
    @SerialName("minecraft:pink_shulker_box")
    PINK_SHULKER_BOX,
    @SerialName("minecraft:gray_shulker_box")
    GRAY_SHULKER_BOX,
    @SerialName("minecraft:light_gray_shulker_box")
    LIGHT_GRAY_SHULKER_BOX,
    @SerialName("minecraft:cyan_shulker_box")
    CYAN_SHULKER_BOX,
    @SerialName("minecraft:purple_shulker_box")
    PURPLE_SHULKER_BOX,
    @SerialName("minecraft:blue_shulker_box")
    BLUE_SHULKER_BOX,
    @SerialName("minecraft:brown_shulker_box")
    BROWN_SHULKER_BOX,
    @SerialName("minecraft:green_shulker_box")
    GREEN_SHULKER_BOX,
    @SerialName("minecraft:red_shulker_box")
    RED_SHULKER_BOX,
    @SerialName("minecraft:black_shulker_box")
    BLACK_SHULKER_BOX,
    @SerialName("minecraft:anvil")
    ANVIL,
    @SerialName("minecraft:chipped_anvil")
    CHIPPED_ANVIL,
    @SerialName("minecraft:damaged_anvil")
    DAMAGED_ANVIL,
    @SerialName("minecraft:enchanting_table")
    ENCHANTING_TABLE,
    @SerialName("minecraft:lectern")
    LECTERN,
    @SerialName("minecraft:grindstone")
    GRINDSTONE,
    @SerialName("minecraft:smithing_table")
    SMITHING_TABLE,
    @SerialName("minecraft:stonecutter")
    STONECUTTER,
    @SerialName("minecraft:composter")
    COMPOSTER,
    @SerialName("minecraft:bell")
    BELL,
    @SerialName("minecraft:bed")
    BED,
    @SerialName("minecraft:white_bed")
    WHITE_BED,
    @SerialName("minecraft:orange_bed")
    ORANGE_BED,
    @SerialName("minecraft:magenta_bed")
    MAGENTA_BED,
    @SerialName("minecraft:light_blue_bed")
    LIGHT_BLUE_BED,
    @SerialName("minecraft:yellow_bed")
    YELLOW_BED,
    @SerialName("minecraft:lime_bed")
    LIME_BED,
    @SerialName("minecraft:pink_bed")
    PINK_BED,
    @SerialName("minecraft:gray_bed")
    GRAY_BED,
    @SerialName("minecraft:light_gray_bed")
    LIGHT_GRAY_BED,
    @SerialName("minecraft:cyan_bed")
    CYAN_BED,
    @SerialName("minecraft:purple_bed")
    PURPLE_BED,
    @SerialName("minecraft:blue_bed")
    BLUE_BED,
    @SerialName("minecraft:brown_bed")
    BROWN_BED,
    @SerialName("minecraft:green_bed")
    GREEN_BED,
    @SerialName("minecraft:red_bed")
    RED_BED,
    @SerialName("minecraft:black_bed")
    BLACK_BED,
    @SerialName("minecraft:jukebox")
    JUKEBOX,
    @SerialName("minecraft:note_block")
    NOTE_BLOCK,
    @SerialName("minecraft:bookshelf")
    BOOKSHELF,
    @SerialName("minecraft:chiseled_bookshelf")
    CHISELED_BOOKSHELF,
    @SerialName("minecraft:flower_pot")
    FLOWER_POT,
    @SerialName("minecraft:painting")
    PAINTING,
    @SerialName("minecraft:item_frame")
    ITEM_FRAME,
    @SerialName("minecraft:glow_item_frame")
    GLOW_ITEM_FRAME,
    @SerialName("minecraft:armor_stand")
    ARMOR_STAND,
    @SerialName("minecraft:lantern")
    LANTERN,
    @SerialName("minecraft:soul_lantern")
    SOUL_LANTERN,
    @SerialName("minecraft:dandelion")
    DANDELION,
    @SerialName("minecraft:poppy")
    POPPY,
    @SerialName("minecraft:blue_orchid")
    BLUE_ORCHID,
    @SerialName("minecraft:allium")
    ALLIUM,
    @SerialName("minecraft:azure_bluet")
    AZURE_BLUET,
    @SerialName("minecraft:red_tulip")
    RED_TULIP,
    @SerialName("minecraft:orange_tulip")
    ORANGE_TULIP,
    @SerialName("minecraft:white_tulip")
    WHITE_TULIP,
    @SerialName("minecraft:pink_tulip")
    PINK_TULIP,
    @SerialName("minecraft:oxeye_daisy")
    OXEYE_DAISY,
    @SerialName("minecraft:cornflower")
    CORNFLOWER,
    @SerialName("minecraft:lily_of_the_valley")
    LILY_OF_THE_VALLEY,
    @SerialName("minecraft:wither_rose")
    WITHER_ROSE,
    @SerialName("minecraft:sunflower")
    SUNFLOWER,
    @SerialName("minecraft:lilac")
    LILAC,
    @SerialName("minecraft:rose_bush")
    ROSE_BUSH,
    @SerialName("minecraft:peony")
    PEONY,
    @SerialName("minecraft:bamboo")
    BAMBOO,
    @SerialName("minecraft:sugar_cane")
    SUGAR_CANE,
    @SerialName("minecraft:cactus")
    CACTUS,
    @SerialName("minecraft:dead_bush")
    DEAD_BUSH,
    @SerialName("minecraft:moss_block")
    MOSS_BLOCK,
    @SerialName("minecraft:moss_carpet")
    MOSS_CARPET,
    @SerialName("minecraft:azalea")
    AZALEA,
    @SerialName("minecraft:flowering_azalea")
    FLOWERING_AZALEA,
    @SerialName("minecraft:spore_blossom")
    SPORE_BLOSSOM,
    @SerialName("minecraft:small_dripleaf")
    SMALL_DRIPLEAF,
    @SerialName("minecraft:big_dripleaf")
    BIG_DRIPLEAF,
    @SerialName("minecraft:big_dripleaf_stem")
    BIG_DRIPLEAF_STEM,
    @SerialName("minecraft:lily_pad")
    LILY_PAD,
    @SerialName("minecraft:vine")
    VINE,
    @SerialName("minecraft:glow_lichen")
    GLOW_LICHEN,
    @SerialName("minecraft:torchflower")
    TORCHFLOWER,
    @SerialName("minecraft:pitcher_plant")
    PITCHER_PLANT,
    @SerialName("minecraft:pitcher_crop")
    PITCHER_CROP,
    @SerialName("minecraft:potted_dandelion")
    POTTED_DANDELION,
    @SerialName("minecraft:potted_poppy")
    POTTED_POPPY,
    @SerialName("minecraft:potted_blue_orchid")
    POTTED_BLUE_ORCHID,
    @SerialName("minecraft:potted_allium")
    POTTED_ALLIUM,
    @SerialName("minecraft:potted_azure_bluet")
    POTTED_AZURE_BLUET,
    @SerialName("minecraft:potted_red_tulip")
    POTTED_RED_TULIP,
    @SerialName("minecraft:potted_orange_tulip")
    POTTED_ORANGE_TULIP,
    @SerialName("minecraft:potted_white_tulip")
    POTTED_WHITE_TULIP,
    @SerialName("minecraft:potted_pink_tulip")
    POTTED_PINK_TULIP,
    @SerialName("minecraft:potted_oxeye_daisy")
    POTTED_OXEYE_DAISY,
    @SerialName("minecraft:potted_cornflower")
    POTTED_CORNFLOWER,
    @SerialName("minecraft:potted_lily_of_the_valley")
    POTTED_LILY_OF_THE_VALLEY,
    @SerialName("minecraft:potted_wither_rose")
    POTTED_WITHER_ROSE,
    @SerialName("minecraft:potted_sunflower")
    POTTED_SUNFLOWER,
    @SerialName("minecraft:potted_lilac")
    POTTED_LILAC,
    @SerialName("minecraft:potted_rose_bush")
    POTTED_ROSE_BUSH,
    @SerialName("minecraft:potted_peony")
    POTTED_PEONY,
    @SerialName("minecraft:potted_fern")
    POTTED_FERN,
    @SerialName("minecraft:potted_cactus")
    POTTED_CACTUS,
    @SerialName("minecraft:potted_bamboo")
    POTTED_BAMBOO,
    @SerialName("minecraft:potted_azalea_bush")
    POTTED_AZALEA_BUSH,
    @SerialName("minecraft:potted_flowering_azalea_bush")
    POTTED_FLOWERING_AZALEA_BUSH,
    @SerialName("minecraft:potted_torchflower")
    POTTED_TORCHFLOWER,
    @SerialName("minecraft:potted_pitcher_plant")
    POTTED_PITCHER_PLANT,
    @SerialName("minecraft:oak_leaves")
    OAK_LEAVES,
    @SerialName("minecraft:spruce_leaves")
    SPRUCE_LEAVES,
    @SerialName("minecraft:birch_leaves")
    BIRCH_LEAVES,
    @SerialName("minecraft:jungle_leaves")
    JUNGLE_LEAVES,
    @SerialName("minecraft:acacia_leaves")
    ACACIA_LEAVES,
    @SerialName("minecraft:dark_oak_leaves")
    DARK_OAK_LEAVES,
    @SerialName("minecraft:mangrove_leaves")
    MANGROVE_LEAVES,
    @SerialName("minecraft:cherry_leaves")
    CHERRY_LEAVES,
    @SerialName("minecraft:azalea_leaves")
    AZALEA_LEAVES,
    @SerialName("minecraft:flowering_azalea_leaves")
    FLOWERING_AZALEA_LEAVES,
    @SerialName("minecraft:beehive")
    BEEHIVE,
    @SerialName("minecraft:bee_nest")
    BEE_NEST,
    @SerialName("minecraft:mushroom_stem")
    MUSHROOM_STEM,
    @SerialName("minecraft:red_mushroom_block")
    RED_MUSHROOM_BLOCK,
    @SerialName("minecraft:brown_mushroom_block")
    BROWN_MUSHROOM_BLOCK,
    @SerialName("minecraft:white_banner")
    WHITE_BANNER,
    @SerialName("minecraft:orange_banner")
    ORANGE_BANNER,
    @SerialName("minecraft:magenta_banner")
    MAGENTA_BANNER,
    @SerialName("minecraft:light_blue_banner")
    LIGHT_BLUE_BANNER,
    @SerialName("minecraft:yellow_banner")
    YELLOW_BANNER,
    @SerialName("minecraft:lime_banner")
    LIME_BANNER,
    @SerialName("minecraft:pink_banner")
    PINK_BANNER,
    @SerialName("minecraft:gray_banner")
    GRAY_BANNER,
    @SerialName("minecraft:light_gray_banner")
    LIGHT_GRAY_BANNER,
    @SerialName("minecraft:cyan_banner")
    CYAN_BANNER,
    @SerialName("minecraft:purple_banner")
    PURPLE_BANNER,
    @SerialName("minecraft:blue_banner")
    BLUE_BANNER,
    @SerialName("minecraft:brown_banner")
    BROWN_BANNER,
    @SerialName("minecraft:green_banner")
    GREEN_BANNER,
    @SerialName("minecraft:red_banner")
    RED_BANNER,
    @SerialName("minecraft:black_banner")
    BLACK_BANNER,
    @SerialName("minecraft:white_wall_banner")
    WHITE_WALL_BANNER,
    @SerialName("minecraft:orange_wall_banner")
    ORANGE_WALL_BANNER,
    @SerialName("minecraft:magenta_wall_banner")
    MAGENTA_WALL_BANNER,
    @SerialName("minecraft:light_blue_wall_banner")
    LIGHT_BLUE_WALL_BANNER,
    @SerialName("minecraft:yellow_wall_banner")
    YELLOW_WALL_BANNER,
    @SerialName("minecraft:lime_wall_banner")
    LIME_WALL_BANNER,
    @SerialName("minecraft:pink_wall_banner")
    PINK_WALL_BANNER,
    @SerialName("minecraft:gray_wall_banner")
    GRAY_WALL_BANNER,
    @SerialName("minecraft:light_gray_wall_banner")
    LIGHT_GRAY_WALL_BANNER,
    @SerialName("minecraft:cyan_wall_banner")
    CYAN_WALL_BANNER,
    @SerialName("minecraft:purple_wall_banner")
    PURPLE_WALL_BANNER,
    @SerialName("minecraft:blue_wall_banner")
    BLUE_WALL_BANNER,
    @SerialName("minecraft:brown_wall_banner")
    BROWN_WALL_BANNER,
    @SerialName("minecraft:green_wall_banner")
    GREEN_WALL_BANNER,
    @SerialName("minecraft:red_wall_banner")
    RED_WALL_BANNER,
    @SerialName("minecraft:black_wall_banner")
    BLACK_WALL_BANNER,
    
    UNKNOWN;
    
    companion object {
        /**
         * Converts a string to BlockID, returning UNKNOWN if parsing fails.
         */
        fun fromString(value: String): BlockID {
            return try {
                Json.decodeFromString<BlockID>("\"$value\"")
            } catch (e: Exception) {
                UNKNOWN
            }
        }
    }
    
    fun isWater(): Boolean = when (this) {
        WATER, ICE, PACKED_ICE, BLUE_ICE, FROSTED_ICE, 
        BUBBLE_COLUMN, KELP, KELP_PLANT, SEAGRASS, 
        TALL_SEAGRASS, WATER_CAULDRON -> true
        else -> false
    }
    
    fun isLog(): Boolean = when (this) {
        OAK_LOG, SPRUCE_LOG, BIRCH_LOG, JUNGLE_LOG, 
        ACACIA_LOG, DARK_OAK_LOG, MANGROVE_LOG, CHERRY_LOG -> true
        else -> false
    }
    
    fun isMushroom(): Boolean = when (this) {
        MUSHROOM_STEM, RED_MUSHROOM_BLOCK, BROWN_MUSHROOM_BLOCK -> true
        else -> false
    }
    
    fun isLeaf(): Boolean = when (this) {
        OAK_LEAVES, SPRUCE_LEAVES, BIRCH_LEAVES, JUNGLE_LEAVES,
        ACACIA_LEAVES, DARK_OAK_LEAVES, MANGROVE_LEAVES, 
        CHERRY_LEAVES, AZALEA_LEAVES, FLOWERING_AZALEA_LEAVES -> true
        else -> false
    }
    
    fun isTree(): Boolean = isLog() || isMushroom()
    
    fun isTreeOrLeaf(): Boolean = isLeaf() || isLog() || isMushroom()
    
    fun isStairs(): Boolean = when (this) {
        OAK_STAIRS, SPRUCE_STAIRS, BIRCH_STAIRS, JUNGLE_STAIRS,
        ACACIA_STAIRS, DARK_OAK_STAIRS, MANGROVE_STAIRS,
        BAMBOO_STAIRS, BAMBOO_MOSAIC_STAIRS, CHERRY_STAIRS,
        CRIMSON_STAIRS, WARPED_STAIRS, SANDSTONE_STAIRS,
        SMOOTH_SANDSTONE_STAIRS, RED_SANDSTONE_STAIRS, SMOOTH_RED_SANDSTONE_STAIRS,
        STONE_STAIRS, COBBLESTONE_STAIRS, MOSSY_COBBLESTONE_STAIRS,
        STONE_BRICK_STAIRS, MOSSY_STONE_BRICK_STAIRS, ANDESITE_STAIRS,
        POLISHED_ANDESITE_STAIRS, DIORITE_STAIRS, POLISHED_DIORITE_STAIRS,
        GRANITE_STAIRS, POLISHED_GRANITE_STAIRS, DEEPSLATE_BRICK_STAIRS,
        DEEPSLATE_TILE_STAIRS, COBBLED_DEEPSLATE_STAIRS, POLISHED_DEEPSLATE_STAIRS,
        TUFF_BRICK_STAIRS, POLISHED_TUFF_STAIRS, BLACKSTONE_STAIRS,
        POLISHED_BLACKSTONE_STAIRS, POLISHED_BLACKSTONE_BRICK_STAIRS,
        NETHER_BRICK_STAIRS, RED_NETHER_BRICK_STAIRS, PRISMARINE_STAIRS,
        PRISMARINE_BRICK_STAIRS, DARK_PRISMARINE_STAIRS, MUD_BRICK_STAIRS,
        QUARTZ_STAIRS, SMOOTH_QUARTZ_STAIRS, PURPUR_STAIRS,
        CUT_COPPER_STAIRS, EXPOSED_CUT_COPPER_STAIRS, WEATHERED_CUT_COPPER_STAIRS,
        OXIDIZED_CUT_COPPER_STAIRS, WAXED_CUT_COPPER_STAIRS,
        WAXED_EXPOSED_CUT_COPPER_STAIRS, WAXED_WEATHERED_CUT_COPPER_STAIRS,
        WAXED_OXIDIZED_CUT_COPPER_STAIRS -> true
        else -> false
    }
    
    fun isSlab(): Boolean = when (this) {
        OAK_SLAB, SPRUCE_SLAB, BIRCH_SLAB, JUNGLE_SLAB,
        ACACIA_SLAB, DARK_OAK_SLAB, MANGROVE_SLAB, BAMBOO_SLAB,
        BAMBOO_MOSAIC_SLAB, CHERRY_SLAB, CRIMSON_SLAB, WARPED_SLAB,
        SANDSTONE_SLAB, CUT_SANDSTONE_SLAB, SMOOTH_SANDSTONE_SLAB,
        RED_SANDSTONE_SLAB, CUT_RED_SANDSTONE_SLAB, SMOOTH_RED_SANDSTONE_SLAB,
        STONE_SLAB, SMOOTH_STONE_SLAB, COBBLESTONE_SLAB, MOSSY_COBBLESTONE_SLAB,
        STONE_BRICK_SLAB, MOSSY_STONE_BRICK_SLAB, ANDESITE_SLAB, POLISHED_ANDESITE_SLAB,
        DIORITE_SLAB, POLISHED_DIORITE_SLAB, GRANITE_SLAB, POLISHED_GRANITE_SLAB,
        COBBLED_DEEPSLATE_SLAB, POLISHED_DEEPSLATE_SLAB, DEEPSLATE_BRICK_SLAB,
        DEEPSLATE_TILE_SLAB, TUFF_BRICK_SLAB, POLISHED_TUFF_SLAB, BLACKSTONE_SLAB,
        POLISHED_BLACKSTONE_SLAB, POLISHED_BLACKSTONE_BRICK_SLAB, NETHER_BRICK_SLAB,
        RED_NETHER_BRICK_SLAB, PRISMARINE_SLAB, PRISMARINE_BRICK_SLAB,
        DARK_PRISMARINE_SLAB, MUD_BRICK_SLAB, QUARTZ_SLAB, SMOOTH_QUARTZ_SLAB,
        PURPUR_SLAB, CUT_COPPER_SLAB, EXPOSED_CUT_COPPER_SLAB,
        WEATHERED_CUT_COPPER_SLAB, OXIDIZED_CUT_COPPER_SLAB, WAXED_CUT_COPPER_SLAB,
        WAXED_EXPOSED_CUT_COPPER_SLAB, WAXED_WEATHERED_CUT_COPPER_SLAB, WAXED_OXIDIZED_CUT_COPPER_SLAB -> true
        else -> false
    }
    
    fun isFence(): Boolean = when (this) {
        OAK_FENCE, SPRUCE_FENCE, BIRCH_FENCE, JUNGLE_FENCE,
        ACACIA_FENCE, DARK_OAK_FENCE, MANGROVE_FENCE, CHERRY_FENCE,
        CRIMSON_FENCE, WARPED_FENCE, NETHER_BRICK_FENCE,
        RED_NETHER_BRICK_FENCE, BAMBOO_FENCE, BAMBOO_MOSAIC_FENCE,
        POLISHED_BLACKSTONE_WALL -> true
        else -> false
    }
}
